# Generated by Django 2.2.4 on 2021-05-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='main.Users'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='on_whish',
            field=models.ManyToManyField(related_name='wishes', to='main.Users'),
        ),
    ]
