# Generated by Django 2.2.4 on 2021-05-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210501_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='date_granted',
            field=models.DateField(auto_now=True),
        ),
    ]
