# Generated by Django 2.2.4 on 2021-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_wishes_date_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='like',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
