# Generated by Django 2.2.4 on 2021-05-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wishes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
