# Generated by Django 2.2.4 on 2021-05-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='granted',
            field=models.IntegerField(default=0),
        ),
    ]
